# Generated by Django 5.0.6 on 2024-06-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_list_lists_items_delete_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Task',
        ),
        migrations.RenameModel(
            old_name='Lists',
            new_name='ToDoList',
        ),
    ]
